#!/usr/bin/env python3
"""WP-PDR-28a: thermal closure of the A5 open items (runner, model extension and checker).

Closes, or routes to the owner, the open thermal items of TS-012 revision 7 section 10 condition 3 for the
chosen design A5 (Mitsubishi RA07M1317M module on the Boyd 530002B02500G sink, printed PETG case, design
items D-1 to D-6), per the PDR work plan revision 6 section 3.0 row 28 (28a):
  (1) long-session cells 58.9 C against 55 C; (2) PETG face at the duty limit 60.1 C against 60 C;
  (3) module case about 106 C against the 90 C guidance; (4) relay ambient 67.1 C against 65 C (with D-5);
  (5) the REQ-SYS-118 NTC on the flange contact face and the firmware duty limit (D-6);
  (6) the REQ-SYS-112 duty-limited corner values for CR-018;
  (7) the bench plan for the in-situ sink and the NTC offset before first on-air use.

It reuses `thermal_model.py` and `ts012_thermal.py` of the TS-012 thermal note (INSP-112) unchanged: both
files are frozen product files of that record, so this runner adds its levers by editing the network that
`thermal_model.build("A5-DC", ...)` returns, never by changing the builder. The A5-DC network is therefore
the reviewed one, node for node.

Layouts of this run (each is A5-DC of the TS-012 note plus the listed changes):
  A5-DC/DL   A5-DC at its junction duty limit, re-found for every input value (INSP-112 finding-15 fix)
  A5-DC/CAP  A5-DC with the firmware key-down duty cap (lever L-1)
  A5-CL      A5-DC with the duty cap (L-1) and the LM2940 tab screwed to the Boyd sink (L-2); the proposed design

Run:    .venv/bin/python hardware/sim/thermal/a5_closure.py [--run-id ID] [--no-ltspice] [--quick]
Check:  .venv/bin/python hardware/sim/thermal/a5_closure.py --check [--run-id ID]
        re-runs everything and compares the verdict-set block and the proposed-values block of the analysis
        record (docs/design/analysis/thermal-budget.md) with the computed ones, and the LTspice cross-check with
        its 0.5 K criterion; prints every difference and exits 1 on any.
LTspice runs only through tools/ltspice-batch.sh (ACC-LTSPICE-001).
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import math
import shutil
import subprocess
import sys
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
sys.path.insert(0, str(HERE))
import thermal_model as m  # noqa: E402
import ts012_thermal as r  # noqa: E402  (sets the Agg backend)

import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402

NOTE = ROOT / "docs/design/analysis/thermal-budget.md"
VS_BEGIN = "<!-- a5-closure-verdicts:begin (generated by a5_closure.py; checked by --check) -->"
VS_END = "<!-- a5-closure-verdicts:end -->"
PV_BEGIN = "<!-- a5-closure-values:begin (generated by a5_closure.py; checked by --check) -->"
PV_END = "<!-- a5-closure-values:end -->"
Param = m.Param
ON_S = r.ON_S  # 13 s key-downs, the longest REQ-SYS-055 allows

# ------------------------------------------------------------------------------------------ inputs added by 28a
P_ADD = {
    # proposed protection values (class R: this record proposes them; the owner rules them at S1 via CR-018)
    "cap_duty": Param(0.35, 0.35, 0.35, "-", "R", "proposed firmware key-down duty cap (this record section 5)"),
    "cap_window": Param(600.0, 600.0, 600.0, "s", "R", "proposed rolling window of the duty cap (this record section 5)"),
    # REQ-SYS-118 NTC on the flange at the body edge (D-6 contact-face placement)
    "ntc_frac_cf": Param(0.20, 0.05, 0.40, "-", "E",
                         "NTC on the flange top at the module body edge (D-6): reading = case - f x (case - sink); "
                         "revision 1 ear-screw placement was 0.5 (0 to 1)"),
    "tau_ntc_cf": Param(5.0, 3.0, 10.0, "s", "E", "Semitec 103AT-2 bonded to the copper flange with thermal epoxy"),
    # LM2940 on the sink (lever L-2)
    "r_lm_jc": Param(1.1, 1.1, 1.1, "K/W", "D", "LM2940 TO-220 RthJC(bot) 1.1 C/W (TI SNVS769J p.5)"),
    "r_lm_if": Param(0.6, 0.4, 1.0, "K/W", "E", "TO-220 tab to the Boyd channel wall, compound, one M3 screw"),
    "c_lm": Param(2.0, 1.5, 3.0, "J/K", "E", "LM2940CT-5.0 TO-220 body and tab"),
    "lm_tj_max": Param(125.0, 125.0, 125.0, "C", "D", "LM2940 NDE operating junction -40 to 125 C (TI SNVS769J p.4)"),
    # REQ-SYS-181 backstop on the sink (D-6 revision 6 for A5)
    "tau_ntc_sink": Param(10.0, 5.0, 20.0, "s", "E", "REQ-SYS-181 103AT-2 on the sink web, compound"),
    "hw_hyst": Param(5.0, 3.0, 10.0, "C", "E", "LM393 cut-off comparator hysteresis (value not yet set)"),
    "tcase_op_max": Param(110.0, 110.0, 110.0, "C", "D", "RA07M1317M Tcase(OP) -30 to +110 C (datasheet Jun 2019 p.2)"),
    "tch_max": Param(175.0, 175.0, 175.0, "C", "D", "RA07M1317M 175 C maximum channel rating (datasheet Jun 2019 p.8)"),
}
PC = dict(m.P)
PC.update(P_ADD)
# Inputs varied by the explicit closed-loop cases, not by the tornado (as in the TS-012 note)
SENSOR_PARAMS = set(r.SENSOR_PARAMS) | {"ntc_frac_cf", "tau_ntc_cf", "tau_ntc_sink", "hw_hyst"}
# The sink-to-air inputs that the in-situ sink measurement replaces (section 7 of the record)
SINK_PATH = {"k_cat", "k_orient", "r_frac", "eta_wall", "eta_guard_dc", "phi_dc", "shield_rad", "o3_rad_amb",
             "o3_rad_guard", "h_gapc", "gap_share", "guard_solid", "v_g", "h_gc", "sink_mass", "cp_al",
             "a_guard_end", "a_guard_side", "a_ew", "t_ew_fr4"}

LAYOUTS = {
    "A5-DC/DL": dict(lm_sink=False, duty="limit"),
    "A5-DC/CAP": dict(lm_sink=False, duty="cap"),
    "A5-CL": dict(lm_sink=True, duty="cap"),
}
COL = {"A5-DC/DL": "#c0504d", "A5-DC/CAP": "#e69f00", "A5-CL": "#1f77b4"}
LABEL = {"A5-DC/DL": "A5-DC at its junction duty limit (TS-012 rev 7 state)",
         "A5-DC/CAP": "A5-DC with the 35 % duty cap (L-1)",
         "A5-CL": "A5-CL: duty cap and LM2940 on the sink (L-1, L-2)"}


def vals(ov: dict | None = None) -> dict:
    v = {k: p.value for k, p in PC.items()}
    if ov:
        v.update(ov)
    return v


def p_lm(v: dict) -> float:
    """LM2940 dissipation of A5-DC (thermal_model.build, with the PWM relay hold of D-5)."""
    i_coil = v["p_relay"] / 5.0
    return v["p_lm2940"] - i_coil * (1.0 - v["relay_hold"]) * (v["v_pack"] - 0.5 - 5.0)


def build(L: str, t_amb: float, v: dict) -> m.Net:
    """A5-DC network of thermal_model.build, then the lever L-2 if the layout has it: the LM2940 heat
    leaves the MAIN node and enters a new LM node tied to the SINK through RthJC(bot) plus the tab joint."""
    net = m.build("A5-DC", t_amb, v)
    net.meta["cl_layout"] = L
    if LAYOUTS[L]["lm_sink"]:
        p = p_lm(v)
        net.src_on["MAIN"] -= p
        net.src_off["MAIN"] -= p
        net.add("LM", v["c_lm"])
        net.link("LM", "SINK", 1.0 / (v["r_lm_jc"] + v["r_lm_if"]))
        net.src("LM", p, p)
        net.meta["p_lm"] = p
    return net


# ------------------------------------------------------------------------------------------ duty
def duty_limit_coupled(L: str, v: dict, lo: float = 0.10, hi: float = 1.0, tol: float = 0.005) -> float:
    """Largest duty (13 s key-downs, periodic steady state) whose junction peak holds tj_limit, by bisection
    (INSP-112 finding-15: re-found for every input value)."""
    net = build(L, 45.0, v)
    if r.periodic_peak(net, hi)[0] <= v["tj_limit"]:
        return hi
    if r.periodic_peak(net, lo)[0] > v["tj_limit"]:
        return 0.0
    while hi - lo > tol:
        mid = 0.5 * (lo + hi)
        if r.periodic_peak(net, mid)[0] <= v["tj_limit"]:
            lo = mid
        else:
            hi = mid
    return lo


def duty_of(L: str, v: dict) -> float:
    return v["cap_duty"] if LAYOUTS[L]["duty"] == "cap" else duty_limit_coupled(L, v)


# ------------------------------------------------------------------------------------------ metrics
METRICS = {
    "tj_pk": "junction peak at the duty (13 s key-downs)",
    "case_d": "module case at the duty, steady",
    "petg_d": "hottest PETG face at the duty",
    "bay_d": "PA-bay air (relay ambient) at the duty",
    "cell_d": "cells, long session at the duty",
    "main_d": "main-bay air, long session at the duty",
    "fr4_d": "FR4 end wall at the duty",
    "cell30": "cells after 30 min at 50 % (TS-012 (a))",
    "main30": "main-bay air after 30 min at 50 % (TS-012 (a))",
    "tj_300": "junction after 5 min continuous from a 45 C soak",
    "tj_180": "junction after 180 s continuous from a 45 C soak",
    "surf5": "hottest accessible surface, 25 C, 5 min",
    "lm_ss": "LM2940 junction, continuous, steady",
    "case_ss": "module case, continuous, steady (no protection)",
    "tj_ss": "junction, continuous, steady (no protection)",
}


def metrics_eval(L: str, v: dict, duty: float | None = None) -> dict:
    d = duty_of(L, v) if duty is None else duty
    net = build(L, 45.0, v)
    T1 = net.steady(1.0)
    Td = net.steady(d)
    ts, xs = net.transient(300.0, 1.0, lambda t: 1.0)
    ij = net.names.index("J2")
    t30, x30 = net.transient(1800.0, 5.0, lambda t: 0.5)
    n25 = build(L, 25.0, v)
    t25, x25 = n25.transient(300.0, 0.5, lambda t: 1.0)
    s5 = m.surfaces(n25, n25.tdict(x25[-1]), v)
    fr4 = m.hot_faces(net, Td, "FR4")
    lm_ss = T1["LM"] if "LM" in T1 else float("nan")
    return dict(duty=d, tj_pk=r.periodic_peak(net, d)[0], case_d=Td["CASE"],
                petg_d=max(m.petg_hot_faces(net, Td, v).values()), bay_d=Td["BAY"], cell_d=Td["CELL"],
                main_d=Td["MAIN"], fr4_d=max(fr4.values()),
                cell30=float(x30[:, net.names.index("CELL")].max()),
                main30=float(x30[:, net.names.index("MAIN")].max()),
                tj_300=float(np.interp(300.0, ts, xs[:, ij])), tj_180=float(np.interp(180.0, ts, xs[:, ij])),
                surf5=max(x for k, x in s5.items() if not k.startswith("SINK (if")),
                lm_ss=lm_ss, case_ss=T1["CASE"], tj_ss=T1["J2"])


def swept_params():
    return [k for k, p in PC.items() if p.low != p.high and p.cls != "R" and k not in SENSOR_PARAMS]


def tornado(L: str, params=None):
    base_v = vals()
    base = metrics_eval(L, base_v)
    rows = []
    for p in (params or swept_params()):
        prm = PC[p]
        if p in P_ADD and not LAYOUTS[L]["lm_sink"] and p in ("r_lm_if", "c_lm"):
            continue  # LM2940 inputs have no effect without L-2
        lo = metrics_eval(L, dict(base_v, **{p: prm.low}))
        hi = metrics_eval(L, dict(base_v, **{p: prm.high}))
        for k in list(METRICS) + ["duty"]:
            if isinstance(base[k], float) and math.isnan(base[k]):
                continue
            rows.append(dict(layout=L, metric=k, param=p, cls=prm.cls, base_value=prm.value, low=prm.low,
                             high=prm.high, out_base=base[k], out_low=lo[k], out_high=hi[k],
                             swing=abs(hi[k] - lo[k])))
    return base, rows


def bands_from(rows, exclude=frozenset()):
    out = {}
    for x in rows:
        if x["param"] in exclude:
            continue
        b = out.setdefault((x["layout"], x["metric"]), dict(layout=x["layout"], metric=x["metric"], up2=0.0,
                                                              dn2=0.0, items=[]))
        up = max(0.0, x["out_low"] - x["out_base"], x["out_high"] - x["out_base"])
        dn = max(0.0, x["out_base"] - x["out_low"], x["out_base"] - x["out_high"])
        b["up2"] += up * up
        b["dn2"] += dn * dn
        b["items"].append((max(up, dn), x["param"], x["cls"]))
    for b in out.values():
        b["up"], b["dn"] = math.sqrt(b["up2"]), math.sqrt(b["dn2"])
        b["items"].sort(reverse=True)
        b["top"] = "; ".join(f"{p} [{c}] {s:.1f} K" for s, p, c in b["items"][:3])
    return out


# ------------------------------------------------------------------------------------------ closed loop
def reading_cf(T: dict, v: dict) -> float:
    return T["CASE"] - v["ntc_frac_cf"] * (T["CASE"] - T["SINK"])


def reading_sink(T: dict, v: dict) -> float:
    return T["SINK"]


def closed_loop(net: m.Net, v: dict, trip: float, hyst: float, tau: float, reading, demand, t_end: float,
                dt: float = 0.1, x0: dict | None = None, every: int = 10):
    """Closed-loop transient with one over-temperature protection: the sensor reading follows reading(T)
    through a first-order lag tau; at reading >= trip the RF ends t_resp later; it re-arms below trip - hyst.
    demand(t) is the operator's key. Returns the maxima of every node and the traces (every `every` steps)."""
    n = len(net.names)
    C = np.array([net.cap[k] for k in net.names])
    x = np.array([x0[k] for k in net.names]) if x0 else np.full(n, net.t_amb)
    a_f = 1.0 - math.exp(-dt / tau)
    s = reading(net.tdict(x), v)
    inhibited, t_off = False, None
    steps = int(round(t_end / dt))
    xmax = x.copy()
    ts, xs, rd, ky = [0.0], [x.copy()], [s], [0.0]
    n_offs = 0
    trips = []
    rf_prev = False
    for k in range(1, steps + 1):
        t = k * dt
        want = demand(t - 0.5 * dt) > 0.5
        rf = want and not (inhibited and t_off is not None and t - 0.5 * dt >= t_off)
        G, b = net._matrix(net.tdict(x))
        x = np.linalg.solve(G + np.diag(C / dt), C / dt * x + net.power(1.0 if rf else 0.0) + b)
        s = s + a_f * (reading(net.tdict(x), v) - s)
        if not inhibited and s >= trip:
            inhibited, t_off = True, t + v["t_resp"]
            trips.append(t)
        elif inhibited and s < trip - hyst:
            inhibited, t_off = False, None
        if rf_prev and not rf and want:
            n_offs += 1
        rf_prev = rf
        xmax = np.maximum(xmax, x)
        if k % every == 0:
            ts.append(t)
            xs.append(x.copy())
            rd.append(s)
            ky.append(1.0 if rf else 0.0)
    return dict(names=list(net.names), t=np.array(ts), x=np.array(xs), reading=np.array(rd), key=np.array(ky),
                max={nm: float(xmax[i]) for i, nm in enumerate(net.names)}, n_offs=n_offs, trips=trips)


def inhibit_cases():
    P = PC
    sens = dict(ntc_frac_cf=P["ntc_frac_cf"].high, tau_ntc_cf=P["tau_ntc_cf"].high)
    adv = dict(sens, a5_rjc2=P["a5_rjc2"].high, a5_bond=P["a5_bond"].high, a5_p1=P["a5_p1"].low, r_feed=0.0)
    return [("nominal", 0.0, {}), ("+3 C tolerance", P["trip_tol"].value, {}),
            ("+3 C, sensor offset and lag adverse", P["trip_tol"].value, sens),
            ("+3 C, sensor, Rth and dissipation adverse", P["trip_tol"].value, adv)]


GOVERNING = "+3 C, sensor offset and lag adverse"


def run_inhibit(L: str, set_c: float, tol: float, ov: dict, t_end: float = 3600.0, demand=None):
    v = vals(ov)
    net = build(L, 45.0, v)
    return closed_loop(net, v, set_c + tol, v["inh_hyst"], v["tau_ntc_cf"], reading_cf,
                       demand or r.demand_cont, t_end), net


def setpoint_for(L: str, tol: float, ov: dict, v0: dict):
    """Largest setpoint on the 0.1 C grid at which the key-held closed loop holds both the junction
    (tj_limit) and the module case (case_guid): bisection between a holding and a failing value, then the
    next 0.1 C up is confirmed to fail."""
    lim_j, lim_c = v0["tj_limit"], v0["case_guid"]

    def holds(sp):
        res, _ = run_inhibit(L, sp, tol, ov)
        return res["max"]["J2"] <= lim_j and res["max"]["CASE"] <= lim_c, res
    lo, hi = 600, 950  # tenths of a degree C: 60.0 C holds, 95.0 C fails (checked below)
    ok_lo, res_lo = holds(lo / 10)
    ok_hi, _ = holds(hi / 10)
    if not ok_lo or ok_hi:
        raise RuntimeError(f"setpoint bracket 60 to 95 C does not bracket the limit for {L}, {ov}")
    while hi - lo > 1:
        mid = (lo + hi) // 2
        ok, res = holds(mid / 10)
        if ok:
            lo, res_lo = mid, res
        else:
            hi = mid
    ok_up, _ = holds((lo + 1) / 10)
    return lo / 10, res_lo, not ok_up


def inhibit_study(L: str, v0: dict):
    rows, traces = [], {}
    cases = inhibit_cases()
    sets = {}
    for name, tol, ov in cases:
        s, res, largest = setpoint_for(L, tol, ov, v0)
        sets[name] = (s, res, largest)
    x_prop = sets[GOVERNING][0]  # the proposed setpoint: sensor adverse at the +3 C edge (as the TS-012 note)
    for name, tol, ov in cases:
        res, net = run_inhibit(L, x_prop, tol, ov)
        v = vals(ov)
        rows.append(dict(layout=L, case=name, tol=tol, overrides=";".join(f"{k}={x:g}" for k, x in ov.items()),
                         setpoint_case=sets[name][0], setpoint_largest=sets[name][2], x_prop=x_prop,
                         tj_max=res["max"]["J2"], case_max=res["max"]["CASE"], sink_max=res["max"]["SINK"],
                         bay_max=res["max"]["BAY"], n_offs=res["n_offs"], p_pa=net.meta["p_pa"],
                         lm_max=res["max"].get("LM", float("nan"))))
        traces[name] = res
    return rows, traces, x_prop


def backstop_study(L: str, v0: dict):
    """REQ-SYS-181 alone (the REQ-SYS-118 inhibit and the duty cap defeated, e.g. firmware hung with the key
    held): the sink NTC trips at the +3 C upper edge (98 C) and re-arms below it less the comparator
    hysteresis. Returns the maxima against the RA07M1317M ratings; also the adverse dissipation case."""
    out = []
    for name, ov in (("nominal", {}), ("Rth and dissipation adverse",
                                        dict(a5_rjc2=PC["a5_rjc2"].high, a5_bond=PC["a5_bond"].high,
                                             a5_p1=PC["a5_p1"].low, r_feed=0.0, tau_ntc_sink=PC["tau_ntc_sink"].high))):
        v = vals(ov)
        net = build(L, 45.0, v)
        res = closed_loop(net, v, v["trip_hw"] + v["trip_tol"], v["hw_hyst"], v["tau_ntc_sink"], reading_sink,
                          r.demand_cont, 3 * 3600.0, dt=0.2, every=10)
        out.append(dict(layout=L, case=name, tj_max=res["max"]["J2"], case_max=res["max"]["CASE"],
                        sink_max=res["max"]["SINK"], lm_max=res["max"].get("LM", float("nan")),
                        n_offs=res["n_offs"], trace=res))
    return out


def cap_pattern(L: str, v0: dict, x_prop: float):
    """The worst pattern the duty cap allows: in every window, one burst of cap_duty x cap_window of held key
    (13 s key-downs re-keyed after 0.5 s), then silence; the inhibit at the proposed setpoint with nominal
    sensor inputs is active. 4 h from a 45 C soak."""
    v = vals()
    W, D = v["cap_window"], v["cap_duty"]

    def demand(t):
        return 1.0 if (t % W) < D * W and r.demand_cont(t % W) > 0.5 else 0.0
    net = build(L, 45.0, v)
    res = closed_loop(net, v, x_prop, v["inh_hyst"], v["tau_ntc_cf"], reading_cf, demand, 4 * 3600.0, dt=0.2,
                      every=25)
    # PETG hot faces along the trace (last hour)
    names = res["names"]
    sel = res["t"] >= 3 * 3600.0
    petg = [max(m.petg_hot_faces(net, dict(zip(names, xx), AMB=net.t_amb), v).values()) for xx in res["x"][sel]]
    res["petg_last_hour_max"] = float(max(petg))
    res["last_hour_max"] = {nm: float(res["x"][sel, i].max()) for i, nm in enumerate(names)}
    res["duty_actual"] = float(res["key"][res["t"] >= 3600.0].mean())
    return res


def duty_limit_S(L: str, v: dict):
    """D-6 alternative: firmware refuses a new key-down while the sink NTC reads above S; S holds 110 C for a
    13 s key-down starting at S (sink rise over 13 s counted without losses, LM2940 heat included). Floored
    to 0.1 C (INSP-112 finding-16 item e)."""
    net = build(L, 45.0, v)
    c = net.cap["SINK"] + net.cap["CASE"] + net.cap.get("LM", 0.0)
    p = net.meta["p_pa"]
    s = v["tj_limit"] - net.meta["p2"] * v["a5_rjc2"] - p * net.meta["r_if"] - (p + net.meta.get("p_lm", 0.0)) * ON_S / c
    s = math.floor(s * 10) / 10
    return s, round(s - v["trip_tol"], 1)


# ------------------------------------------------------------------------------------------ bench acceptance
def bench_R(L: str, v: dict, p_b: float) -> float:
    """Model of the bench coupon: the A5-CL network at 25 C with every source removed and p_b on the sink."""
    net = build(L, 25.0, v)
    net.src_on = {"SINK": p_b}
    net.src_off = {"SINK": p_b}
    T = net.steady(1.0)
    return (T["SINK"] - 25.0) / p_b


def bench_acceptance(L: str, bands_ns: dict, v0: dict):
    """Sweep the sink-to-air path through k_orient (which scales the whole catalog conductance) and find the
    in-situ resistance at which the duty-cap junction peak plus the band of the inputs the bench does not
    replace reaches 110 C, and the module case plus its band reaches 90 C."""
    ko = np.round(np.arange(0.9, 2.61, 0.05), 3)
    rows = []
    for k in ko:
        v = vals(dict(k_orient=float(k)))
        net = build(L, 45.0, v)
        d = v["cap_duty"]
        pk = r.periodic_peak(net, d)[0]
        Td = net.steady(d)
        rows.append(dict(k_orient=float(k), R5=bench_R(L, v, 5.0), R10=bench_R(L, v, 10.0), tj_pk=pk,
                         case_d=Td["CASE"], cell_d=Td["CELL"], petg_d=max(m.petg_hot_faces(net, Td, v).values())))
    bj, bc = bands_ns[(L, "tj_pk")]["up"], bands_ns[(L, "case_d")]["up"]
    tj = np.array([x["tj_pk"] for x in rows])
    cs = np.array([x["case_d"] for x in rows])
    R5 = np.array([x["R5"] for x in rows])
    R10 = np.array([x["R10"] for x in rows])
    # tj and case rise monotonically with k_orient; interpolate the limit crossings
    kj = float(np.interp(v0["tj_limit"] - bj, tj, ko))
    kc = float(np.interp(v0["case_guid"] - bc, cs, ko))
    k_acc = min(kj, kc)
    r5_acc = bench_R(L, vals(dict(k_orient=k_acc)), 5.0)
    r10_acc = bench_R(L, vals(dict(k_orient=k_acc)), 10.0)
    return dict(rows=rows, band_tj=bj, band_case=bc, k_tj=kj, k_case=kc, k_acc=k_acc,
                R5_acc=math.floor(r5_acc * 100) / 100, R10_acc=math.floor(r10_acc * 100) / 100,
                R5_nom=bench_R(L, vals(), 5.0), R10_nom=bench_R(L, vals(), 10.0),
                R5=R5, R10=R10, ko=ko, tj=tj, cs=cs)


# ------------------------------------------------------------------------------------------ verdict set
CRITERIA = [
    ("C01", "Junction peak at the duty, 13 s key-downs, 45 C", "tj_pk", "tj_limit", None, "REQ-SYS-112 delta (proposed corner)"),
    ("C02", "Module case at the duty, steady", "case_d", "case_guid", None, "RA07M1317M p.8 long-term guidance"),
    ("C03", "Hottest PETG face at the duty", "petg_d", "petg_crit", None, "TS-012 7.3 (c)"),
    ("C04", "PA-bay air (relay ambient) at the duty", "bay_d", "relay_amb", None, "G5V-2 ambient rating"),
    ("C05", "Cells, long session at the duty, steady", "cell_d", "cell_crit_a", None, "TS-012 7.3 (a), extended"),
    ("C06", "Main-bay air, long session at the duty", "main_d", "cell_crit_a", None, "TS-012 7.3 (a), extended"),
    ("C07", "FR4 end wall at the duty", "fr4_d", "fr4_limit", None, "design limit (E)"),
    ("C08", "Cells after 30 min at 50 % duty", "cell30", "cell_crit_a", None, "TS-012 7.3 (a)"),
    ("C09", "Main-bay air after 30 min at 50 % duty", "main30", "cell_crit_a", None, "TS-012 7.3 (a)"),
    ("C10", "Junction after 5 min continuous from a 45 C soak", "tj_300", "tj_limit", None, "HZ-003 K7"),
    ("C11", "Junction after 180 s continuous from a 45 C soak", "tj_180", "tj_limit", None, "HZ-003 K10"),
    ("C12", "Hottest accessible surface, 25 C, 5 min", "surf5", "surf_limit", None, "REQ-SYS-113 (TBR)"),
]
SHORT = {"nominal": "nominal", "+3 C tolerance": "+3 C tolerance",
         "+3 C, sensor offset and lag adverse": "+3 C, sensor adverse",
         "+3 C, sensor, Rth and dissipation adverse": "+3 C, all adverse",
         "Rth and dissipation adverse": "Rth and dissipation adverse"}


def up1(x):
    return math.ceil(round(x * 10, 6)) / 10


def dn1(x):
    return math.floor(round(x * 10, 6)) / 10


def verdict_set(base, bands, inh_rows, bs_rows, v0):
    out = []
    for cid, text, key, limk, lays, basis in CRITERIA:
        for L in LAYOUTS:
            if lays is not None and L not in lays:
                continue
            x = base[L][key]
            lim = v0[limk]
            b = bands[(L, key)]
            verdict = "FAIL" if x > lim else ("OPEN" if x + b["up"] > lim else "PASS")
            out.append(dict(id=cid, tag=key, criterion=text, basis=basis, layout=L, value=x, limit=lim, margin=lim - x,
                            band_up=b["up"], band_dn=b["dn"], verdict=verdict, drivers=b["top"]))
    k = len(CRITERIA) + 1
    for key, limk, what in (("tj_max", "tj_limit", "Junction"), ("case_max", "case_guid", "Module case")):
        for case in [c[0] for c in inhibit_cases()]:
            for row in inh_rows:
                if row["case"] != case:
                    continue
                x, lim = row[key], v0[limk]
                out.append(dict(id=f"C{k:02d}", tag=f"inh:{key}:{case}", criterion=f"{what}, inhibit at the proposed setpoint, key held: {SHORT[case]}",
                                basis="REQ-SYS-118, HZ-003 K2", layout=row["layout"], value=x, limit=lim,
                                margin=lim - x, band_up=0.0, band_dn=0.0, verdict="FAIL" if x > lim else "PASS",
                                drivers="explicit closed-loop case"))
            k += 1
    for row in inh_rows:
        if row["case"] == GOVERNING:
            x = row["sink_max"]
            lim = v0["trip_hw"] - v0["trip_tol"]
            out.append(dict(id=f"C{k:02d}", tag="inh:sink", criterion="Sink, inhibit at the proposed setpoint, key held: +3 C, sensor adverse",
                            basis="REQ-SYS-181 92 C lower edge", layout=row["layout"], value=x, limit=lim,
                            margin=lim - x, band_up=0.0, band_dn=0.0, verdict="FAIL" if x > lim else "PASS",
                            drivers="explicit closed-loop case"))
    k += 1
    for key, limk, what, basis in (("tj_max", "tch_max", "Channel", "RA07M1317M p.8 rating"),
                                   ("case_max", "tcase_op_max", "Module case", "RA07M1317M p.2 Tcase(OP)"),
                                   ("lm_max", "lm_tj_max", "LM2940 junction", "TI SNVS769J p.4")):
        for row in bs_rows:
            x, lim = row[key], v0[limk]
            out.append(dict(id=f"C{k:02d}", tag=f"bs:{key}:{row['case']}", criterion=f"{what}, only the REQ-SYS-181 cut-off acting at 98 C, key held: {SHORT[row['case']]}",
                            basis=basis, layout=row["layout"], value=x, limit=lim,
                            margin=lim - x, band_up=0.0, band_dn=0.0, verdict="FAIL" if x > lim else "PASS",
                            drivers="explicit closed-loop case"))
            k += 1
    return out


def render_block(vs):
    lays = list(LAYOUTS)
    lines = [VS_BEGIN, "", "| Id | Criterion (basis) | Limit, C | " + " | ".join(lays) + " |",
             "|---|---|---|" + "---|" * len(lays)]
    for cid in dict.fromkeys(x["id"] for x in vs):
        rr = {x["layout"]: x for x in vs if x["id"] == cid}
        first = next(iter(rr.values()))
        cells = []
        for L in lays:
            x = rr.get(L)
            if x is None:
                cells.append("-")
                continue
            band = f" +{up1(x['band_up']):.1f}" if x["band_up"] > 0 else ""
            cells.append(f"{up1(x['value']):.1f}{band} **{x['verdict']}**")
        lines.append(f"| {cid} | {first['criterion']} ({first['basis']}) | {first['limit']:.0f} | " + " | ".join(cells) + " |")
    lines += ["", VS_END]
    return "\n".join(lines)


def render_values(base, inh_rows, x_prop, S, bench, v0, cp, vs):
    """The proposed values, generated (INSP-112 finding-16: no hand transcription of proposed values)."""
    gov = next(x for x in inh_rows if x["case"] == GOVERNING)
    alladv = next(x for x in inh_rows if x["case"].startswith("+3 C, sensor, Rth"))
    b = base["A5-CL"]
    ids = {x["tag"]: x["id"] for x in vs}
    box = [ids[k] for k in ("tj_pk", "case_d", "petg_d", "bay_d", "cell_d", "main_d")]
    bsid = sorted(x["id"] for x in vs if x["tag"].startswith("bs:"))
    lines = [PV_BEGIN, "",
             "| Item | Proposed value (A5-CL) | Basis in this run |",
             "|---|---|---|",
             f"| Firmware key-down duty cap (REQ-SYS-112 corner) | at most {v0['cap_duty'] * 100:.0f} % key-down time in any rolling {v0['cap_window'] / 60:.0f} min window | "
             f"junction peak {up1(b['tj_pk']):.1f} C and every box criterion within its limit at {v0['cap_duty'] * 100:.0f} % ({box[0]} to {box[-1]}); worst burst pattern under the cap: cells {up1(cp['last_hour_max']['CELL']):.1f} C, PETG {up1(cp['petg_last_hour_max']):.1f} C |",
             f"| REQ-SYS-118 threshold at the flange NTC (as programmed, the +3 C tolerance above it) | {x_prop:.1f} C | "
             f"largest 0.1 C value holding the junction at 110 C and the case at 90 C, key held, sensor offset and lag adverse ({ids['inh:tj_max:' + GOVERNING]}, {ids['inh:case_max:' + GOVERNING]}: {up1(gov['tj_max']):.1f} C, {up1(gov['case_max']):.1f} C) |",
             f"| REQ-SYS-118 threshold if every input is adverse (for the bench rule) | {alladv['setpoint_case']:.1f} C | the all-adverse stack of {ids['inh:tj_max:' + alladv['case']]} and {ids['inh:case_max:' + alladv['case']]} |",
             f"| D-6 alternative, sink-NTC duty limit S (to program, +3 C taken off) | {S[1]:.1f} C (S = {S[0]:.1f} C) | 13 s key-down from S holds 110 C; floored |",
             f"| REQ-SYS-181 cut-off | 95 C +/-3 C on the sink, 100 ms: confirmed | channel, case and LM2940 with only the cut-off acting ({bsid[0]} to {bsid[-1]}) within 175 C, 110 C and 125 C |",
             f"| In-situ sink acceptance (bench, 5.0 W on the web, 25 C room) | at most {bench['R5_acc']:.2f} K/W (model nominal {bench['R5_nom']:.2f}) | junction peak plus the non-sink band at 110 C, case plus its band at 90 C |",
             f"| In-situ sink acceptance (bench, 10.0 W) | at most {bench['R10_acc']:.2f} K/W (model nominal {bench['R10_nom']:.2f}) | same, read at 10 W |",
             "", PV_END]
    return "\n".join(lines)


# ------------------------------------------------------------------------------------------ LTspice
def ltspice_check(out: Path, L: str = "A5-CL"):
    d = out / "ltspice"
    d.mkdir(exist_ok=True)
    v = vals()
    net = build(L, 45.0, v)
    duty = v["cap_duty"]
    T = net.steady(duty)
    lin = net.linearized(T)
    deck = d / "thermal_a5cl.net"
    p_avg = net.power(duty)
    lines = [f"* cwht WP-PDR-28a thermal network {L}, electrical analogue (1 V = 1 C, 1 A = 1 W, 1 ohm = 1 K/W, 1 F = 1 J/K)",
             f"* conductances frozen at the Python steady state at the {duty * 100:.0f} % duty cap, 45 C; average power",
             "* generated by hardware/sim/thermal/a5_closure.py; run with tools/ltspice-batch.sh",
             "VAMB amb 0 45"]
    for k, (a, b, g) in enumerate(lin, 1):
        lines.append(f"R{k} {a.lower()} {'amb' if b == 'AMB' else b.lower()} {1.0 / g:.9g}")
    for k, n in enumerate(net.names, 1):
        lines.append(f"C{k} {n.lower()} 0 {net.cap[n]:.9g}")
    for k, (n, p) in enumerate(zip(net.names, p_avg), 1):
        if p != 0.0:
            lines.append(f"I{k} 0 {n.lower()} {p:.9g}")
    lines += [".ic " + " ".join(f"V({n.lower()})=45" for n in net.names), ".tran 0 14400 0 4",
              ".meas tran cell_end FIND V(cell) AT=14400", ".meas tran j2_end FIND V(j2) AT=14400", ".end"]
    deck.write_text("\n".join(lines) + "\n")
    pr = subprocess.run([str(ROOT / "tools/ltspice-batch.sh"), "-t", "240", "-o", str(d), "-b", str(deck)],
                        capture_output=True, text=True)
    (d / "ltspice-batch.stderr.txt").write_text(pr.stdout + pr.stderr)
    if pr.returncode != 0:
        return dict(ok=False, rc=pr.returncode, msg=pr.stderr[-2000:])
    from spicelib import RawRead
    raw = RawRead(str(d / "thermal_a5cl.raw"))
    t_lt = np.abs(np.array(raw.get_trace("time").get_wave(0), dtype=float))
    lnet = m.Net(t_amb=45.0)
    for n in net.names:
        lnet.add(n, net.cap[n])
    for a, b, g in lin:
        lnet.link(a, b, g)
    for n, p in zip(net.names, p_avg):
        lnet.src(n, p)
    ts, xs = lnet.transient(14400.0, 1.0, lambda t: 1.0, every=4)
    fig, ax = plt.subplots(figsize=(9, 5))
    res, maxdiff = {}, 0.0
    for n, c in (("J2", "#c0504d"), ("CASE", "#8064a2"), ("SINK", "#1f77b4"), ("LM", "#7f7f7f"), ("BAY", "#e69f00"),
                 ("MAIN", "#9e480e"), ("CELL", "#2ca02c")):
        y_lt = np.array(raw.get_trace(f"V({n.lower()})").get_wave(0), dtype=float)
        y_py = np.interp(t_lt, ts, xs[:, net.names.index(n)])
        diff = float(np.max(np.abs(y_lt - y_py)[t_lt > 30]))
        maxdiff = max(maxdiff, diff)
        res[n] = dict(lt_end=float(y_lt[-1]), py_end=float(xs[-1, net.names.index(n)]), ss=T[n], maxdiff=diff)
        ax.plot(t_lt / 60, y_lt, color=c, lw=2.5, alpha=0.45, label=f"{n} LTspice")
        ax.plot(ts / 60, xs[:, net.names.index(n)], color=c, lw=1.0, ls="--", label=f"{n} Python")
    ax.set_xlabel(f"time, min (45 C soak, average power of the {duty * 100:.0f} % duty cap)")
    ax.set_ylabel("temperature, C")
    ax.set_title(f"LTspice electrical analogue vs Python solver, {L} linearized at the duty cap\n"
                 f"max |difference| after 30 s = {maxdiff:.3f} K (pass criterion 0.5 K)")
    ax.grid(alpha=0.3)
    ax.legend(fontsize=7, ncol=2)
    fig.tight_layout()
    fig.savefig(out / "cl_ltspice_crosscheck.png", dpi=130)
    plt.close(fig)
    return dict(ok=True, maxdiff=maxdiff, nodes=res, deck_sha256=hashlib.sha256(deck.read_bytes()).hexdigest())


# ------------------------------------------------------------------------------------------ plots
LIM = {"tj_pk": ("tj_limit", "REQ-SYS-112 110 C"), "case_d": ("case_guid", "module case 90 C guidance"),
       "petg_d": ("petg_crit", "PETG 60 C"), "bay_d": ("relay_amb", "G5V-2 ambient 65 C"),
       "cell_d": ("cell_crit_a", "cells 55 C (60 C trip dashed)"), "main_d": ("cell_crit_a", "main-bay air 55 C")}


def plot_vs_duty(out: Path, sweep, base, bands, v0):
    fig, axs = plt.subplots(2, 3, figsize=(17, 10))
    for ax, key in zip(axs.flat, LIM):
        for L in ("A5-DC/CAP", "A5-CL"):
            rows = sweep[L]
            ax.plot([x["duty"] * 100 for x in rows], [x[key] for x in rows], "-o", ms=3, color=COL[L],
                    label=("A5-DC (TS-012 rev 7 design items)" if L == "A5-DC/CAP" else LABEL["A5-CL"].split(":")[0] + ": LM2940 on the sink (L-2)"))
            b = bands[(L, key)]
            d = v0["cap_duty"] * 100
            ax.errorbar([d + (0.6 if L == "A5-CL" else -0.6)], [base[L][key]], yerr=[[b["dn"]], [b["up"]]], fmt="s",
                        color=COL[L], capsize=4, ms=6)
        bdl = base["A5-DC/DL"]
        ax.plot([bdl["duty"] * 100], [bdl[key]], "D", color=COL["A5-DC/DL"], ms=7,
                label=f"A5-DC at its junction duty limit {bdl['duty'] * 100:.1f} % (rev 7 state)")
        lk, lt = LIM[key]
        ax.axhline(v0[lk], color="k", lw=1.3)
        ax.text(21, v0[lk] + 0.3, lt, fontsize=8)
        if key == "cell_d":
            ax.axhline(v0["cell_limit"], color="k", lw=0.8, ls="--")
        ax.axvline(v0["cap_duty"] * 100, color="#555", lw=0.8, ls=":")
        ax.text(v0["cap_duty"] * 100 + 0.5, 0.97, f"proposed cap {v0['cap_duty'] * 100:.0f} %", fontsize=7, color="#555",
                va="top", transform=ax.get_xaxis_transform())
        ax.set_xlabel("key-down duty, % (13 s key-downs, 45 C, steady)")
        lo_, hi_ = ax.get_ylim()
        ax.set_ylim(lo_, max(hi_, v0[lk] + 1.5))
        ax.set_title(METRICS[key], fontsize=10)
        ax.set_ylabel("C")
        ax.grid(alpha=0.3)
        ax.legend(fontsize=7, loc="lower right")
    fig.suptitle("A5 at 45 C ambient: junction, module case and box temperatures versus key-down duty, with and without "
                 "the LM2940 on the sink\n(squares: value at the proposed cap with its RSS band of all swept inputs)")
    fig.tight_layout()
    fig.savefig(out / "cl_box_vs_duty.png", dpi=120)
    plt.close(fig)


def plot_margins(out: Path, vs):
    fig, axs = plt.subplots(1, 3, figsize=(21, 11), sharex=True)
    cmap = {"PASS": "#2ca02c", "OPEN": "#e69f00", "FAIL": "#c0504d"}
    for ax, L in zip(axs, LAYOUTS):
        rr = [x for x in vs if x["layout"] == L]
        y = np.arange(len(rr))[::-1]
        for yy, x in zip(y, rr):
            ax.errorbar(x["margin"], yy, xerr=[[x["band_up"]], [x["band_dn"]]], fmt="o", color=cmap[x["verdict"]],
                        ecolor="#555", capsize=3, ms=6)
            ax.text(1.01, yy, f"{x['verdict']} {x['margin']:+.1f}", fontsize=7, va="center", color=cmap[x["verdict"]],
                    transform=ax.get_yaxis_transform(), clip_on=False)
        ax.axvline(0, color="k", lw=1.5)
        ax.axvspan(-30, 0, color="#c0504d", alpha=0.07)
        ax.set_yticks(y)
        ax.set_yticklabels([f"{x['id']} {x['criterion'][:78]}" for x in rr], fontsize=6.5)
        ax.set_xlim(-30, 80)
        ax.grid(alpha=0.3, axis="x")
        ax.set_title(LABEL[L], fontsize=9)
        ax.set_xlabel("margin to the limit, K (bars: RSS band)")
    fig.suptitle("WP-PDR-28a verdict set: margin to each limit with its band (left of 0 fails; a band crossing 0 is OPEN)")
    fig.tight_layout(rect=(0, 0, 0.97, 1))
    fig.savefig(out / "cl_margins.png", dpi=110)
    plt.close(fig)


def plot_inhibit(out: Path, traces, rows, bs, v0, x_prop):
    fig, axs = plt.subplots(2, 2, figsize=(16, 11))
    cc = ["#2ca02c", "#1f77b4", "#e69f00", "#c0504d"]
    rmap = {x["case"]: x for x in rows}
    for k, (name, tr) in enumerate(traces.items()):
        ij, ic = tr["names"].index("J2"), tr["names"].index("CASE")
        axs[0, 0].plot(tr["t"] / 60, tr["x"][:, ij], color=cc[k], lw=0.8,
                       label=f"{name}: max {rmap[name]['tj_max']:.1f} C")
        axs[0, 1].plot(tr["t"] / 60, tr["x"][:, ic], color=cc[k], lw=0.8,
                       label=f"{name}: max {rmap[name]['case_max']:.1f} C; own setpoint {rmap[name]['setpoint_case']:.1f} C")
    for ax, lim, lab in ((axs[0, 0], v0["tj_limit"], "junction limit 110 C"), (axs[0, 1], v0["case_guid"], "module case 90 C guidance")):
        ax.axhline(lim, color="k", lw=1.3)
        ax.text(0.5, lim + 0.5, lab, fontsize=8)
        ax.set_xlim(0, 60)
        ax.set_xlabel("time, min (45 C soak; key held: 13 s key-downs re-keyed after 0.5 s)")
        ax.set_ylabel("C")
        ax.grid(alpha=0.3)
        ax.legend(fontsize=7.5, loc="lower right")
    axs[0, 0].set_title(f"A5-CL junction with the REQ-SYS-118 inhibit at {x_prop:.1f} C on the flange NTC (closed loop)", fontsize=9)
    axs[0, 1].set_title(f"A5-CL module case, same runs (the setpoint holds both limits)", fontsize=9)
    ax = axs[1, 0]
    tr = traces[GOVERNING]
    tt = tr["t"]
    t0 = float(tr["trips"][0]) if tr["trips"] else 600.0
    sel = (tt > t0 - 60) & (tt < t0 + 60)
    for n, c, lab in (("J2", "#c0504d", "junction"), ("CASE", "#8064a2", "module case (true)"), ("SINK", "#1f77b4", "sink")):
        ax.plot(tt[sel], tr["x"][sel, tr["names"].index(n)], color=c, lw=1.4, label=lab)
    ax.plot(tt[sel], tr["reading"][sel], color="k", lw=1.2, ls="--", label="flange NTC reading (offset and lag adverse)")
    ax.axhline(x_prop + v0["trip_tol"], color="k", lw=0.8, ls=":")
    ax.text(t0 - 59, x_prop + v0["trip_tol"] + 0.4, f"trip at the +3 C edge, {x_prop + v0['trip_tol']:.1f} C", fontsize=8)
    ax.set_xlabel("time, s")
    ax.set_ylabel("C")
    ax.axvline(t0, color="#555", lw=0.8)
    ax.set_title(f"Zoom on the first trip (at {t0 / 60:.1f} min), {GOVERNING}", fontsize=9)
    ax.grid(alpha=0.3)
    ax.legend(fontsize=8, loc="upper left")
    ax = axs[1, 1]
    for rr, cs in zip(bs, (("#c0504d", "#8064a2", "#1f77b4"), ("#e69f00", "#2ca02c", "#7f7f7f"))):
        tr = rr["trace"]
        sel = tr["t"] <= 3600.0
        for n, c, lab in (("J2", cs[0], f"channel, {rr['case']}: max {rr['tj_max']:.1f} C"),
                          ("CASE", cs[1], f"module case, {rr['case']}: max {rr['case_max']:.1f} C"),
                          ("SINK", cs[2], f"sink, {rr['case']}: max {rr['sink_max']:.1f} C")):
            ax.plot(tr["t"][sel] / 60, tr["x"][sel, tr["names"].index(n)], color=c, lw=0.8, label=lab)
    ax.axhline(v0["tcase_op_max"], color="k", lw=1.0)
    ax.text(1, v0["tcase_op_max"] + 0.8, "Tcase(OP) maximum 110 C (p.2)", fontsize=8)
    ax.axhline(v0["trip_hw"] + v0["trip_tol"], color="#555", lw=0.8, ls=":")
    ax.text(1, v0["trip_hw"] + v0["trip_tol"] - 3, "REQ-SYS-181 trip at its 98 C upper edge (sink)", fontsize=8)
    ax.set_ylim(60, 180)
    ax.axhline(v0["tch_max"], color="k", lw=1.0)
    ax.text(1, v0["tch_max"] - 4, "channel rating 175 C (p.8)", fontsize=8)
    ax.set_xlabel("time, min, first hour of 3 h (inhibit and duty cap defeated, key held, 45 C soak)")
    ax.set_ylabel("C")
    ax.set_title("REQ-SYS-181 backstop alone on the sink NTC", fontsize=9)
    ax.grid(alpha=0.3)
    ax.legend(fontsize=7, loc="lower right")
    fig.suptitle("A5-CL thermal protection in closed loop: REQ-SYS-118 inhibit on the flange NTC, and the REQ-SYS-181 backstop")
    fig.tight_layout()
    fig.savefig(out / "cl_inhibit_backstop.png", dpi=120)
    plt.close(fig)


def plot_cap(out: Path, cp, base, v0):
    fig, axs = plt.subplots(2, 1, figsize=(14, 10), sharex=True)
    t = cp["t"] / 3600
    for n, c in (("J2", "#c0504d"), ("CASE", "#8064a2"), ("SINK", "#1f77b4"), ("LM", "#7f7f7f")):
        axs[0].plot(t, cp["x"][:, cp["names"].index(n)], color=c, lw=0.7, label=f"{n}: last-hour max {cp['last_hour_max'][n]:.1f} C")
    axs[0].axhline(v0["tj_limit"], color="k", lw=1.2)
    axs[0].axhline(v0["case_guid"], color="k", lw=0.8, ls="--")
    axs[0].text(0.02, v0["tj_limit"] + 0.8, "110 C junction", fontsize=8)
    axs[0].text(0.02, v0["case_guid"] + 0.8, "90 C module case", fontsize=8)
    axs[0].set_ylabel("C")
    axs[0].legend(fontsize=8, loc="lower right")
    axs[0].grid(alpha=0.3)
    axs[0].set_title(f"A5-CL, worst pattern the cap allows: {v0['cap_duty'] * v0['cap_window'] / 60:.1f} min of held key in every "
                     f"{v0['cap_window'] / 60:.0f} min window, inhibit active; measured key-down fraction after 1 h {cp['duty_actual'] * 100:.1f} %", fontsize=10)
    for n, c, lim in (("CELL", "#2ca02c", "cell_crit_a"), ("MAIN", "#9e480e", "cell_crit_a"), ("BAY", "#e69f00", "relay_amb")):
        axs[1].plot(t, cp["x"][:, cp["names"].index(n)], color=c, lw=0.9,
                    label=f"{n}: last-hour max {cp['last_hour_max'][n]:.1f} C (steady at the cap {base['A5-CL'][{'CELL': 'cell_d', 'MAIN': 'main_d', 'BAY': 'bay_d'}[n]]:.1f} C)")
    axs[1].axhline(v0["cell_crit_a"], color="k", lw=1.2)
    axs[1].axhline(v0["relay_amb"], color="k", lw=0.8, ls="--")
    axs[1].text(0.02, v0["cell_crit_a"] + 0.3, "55 C cells and main-bay air", fontsize=8)
    axs[1].text(0.02, v0["relay_amb"] + 0.3, "65 C relay ambient", fontsize=8)
    axs[1].text(2.0, 47, f"hottest PETG face in the last hour {cp['petg_last_hour_max']:.1f} C (limit 60 C)", fontsize=9)
    axs[1].set_ylim(44, 68)
    axs[1].set_xlabel("time from a 45 C soak, h")
    axs[1].set_ylabel("C")
    axs[1].legend(fontsize=8, loc="lower right")
    axs[1].grid(alpha=0.3)
    fig.tight_layout()
    fig.savefig(out / "cl_cap_pattern.png", dpi=120)
    plt.close(fig)


def plot_bench(out: Path, bench, v0):
    fig, ax = plt.subplots(figsize=(10, 6))
    ax.plot(bench["R5"], bench["tj"], "-", color="#c0504d", label=f"junction peak at the {v0['cap_duty'] * 100:.0f} % cap, 45 C")
    ax.plot(bench["R5"], bench["cs"], "-", color="#8064a2", label=f"module case at the {v0['cap_duty'] * 100:.0f} % cap, 45 C")
    ax.axhline(v0["tj_limit"] - bench["band_tj"], color="#c0504d", lw=1, ls="--")
    ax.text(bench["R5"][0], v0["tj_limit"] - bench["band_tj"] + 0.5,
            f"110 C less the band of the inputs the bench does not replace ({bench['band_tj']:.1f} K)", fontsize=8, color="#c0504d")
    ax.axhline(v0["case_guid"] - bench["band_case"], color="#8064a2", lw=1, ls="--")
    ax.text(bench["R5"][0], v0["case_guid"] - bench["band_case"] + 0.5,
            f"90 C less its band ({bench['band_case']:.1f} K)", fontsize=8, color="#8064a2")
    ax.axvline(bench["R5_nom"], color="#1f77b4", lw=1)
    ax.text(bench["R5_nom"] + 0.03, 0.03, f"model nominal {bench['R5_nom']:.2f} K/W", fontsize=8, color="#1f77b4", rotation=90,
            transform=ax.get_xaxis_transform())
    ax.axvline(bench["R5_acc"], color="k", lw=1.6)
    ax.text(bench["R5_acc"] + 0.03, 0.03, f"acceptance: at most {bench['R5_acc']:.2f} K/W", fontsize=9, rotation=90,
            transform=ax.get_xaxis_transform())
    ax.axvspan(bench["R5_acc"], bench["R5"][-1], color="#c0504d", alpha=0.07)
    ax.set_xlabel("in-situ sink-to-air resistance on the bench, K/W (5.0 W on the web, guard and FR4 end-wall coupon, "
                  "extrusion horizontal, 25 C room)")
    ax.set_ylabel("C")
    ax.set_title("Bench acceptance of the in-situ sink (item 7): the swept input is the orientation derate k_orient "
                 f"{bench['ko'][0]:.2f} to {bench['ko'][-1]:.2f}", fontsize=10)
    ax.grid(alpha=0.3)
    ax.legend(fontsize=8, loc="upper left")
    fig.tight_layout()
    fig.savefig(out / "cl_bench_acceptance.png", dpi=125)
    plt.close(fig)


def plot_tornado(out: Path, rows, bands):
    cols = [("tj_pk", 110.0), ("case_d", 90.0), ("petg_d", 60.0), ("bay_d", 65.0), ("cell_d", 55.0), ("main_d", 55.0)]
    fig, axs = plt.subplots(2, 3, figsize=(24, 12))
    for ax, (key, lim) in zip(axs.flat, cols):
        rr = sorted([x for x in rows if x["layout"] == "A5-CL" and x["metric"] == key], key=lambda x: x["swing"],
                    reverse=True)[:12][::-1]
        base = rr[0]["out_base"]
        for k, x in enumerate(rr):
            ax.barh(k, x["out_low"] - base, left=base, color="#1f77b4", alpha=0.8)
            ax.barh(k, x["out_high"] - base, left=base, color="#c0504d", alpha=0.8)
        ax.set_yticks(range(len(rr)))
        ax.set_yticklabels([f"{x['param']} [{x['cls']}] {x['low']:.3g}/{x['high']:.3g}" for x in rr], fontsize=7)
        b = bands[("A5-CL", key)]
        ax.axvspan(base - b["dn"], base + b["up"], color="#999", alpha=0.18, label="RSS band of all inputs")
        ax.axvline(base, color="k", lw=1)
        ax.axvline(lim, color="k", lw=1.6, ls="--")
        ax.text(lim, len(rr) - 0.4, f" limit {lim:.0f} C", fontsize=8)
        ax.set_title(f"A5-CL {METRICS[key]}\nbase {base:.2f} C, band -{b['dn']:.1f} / +{b['up']:.1f} K", fontsize=9)
        ax.set_xlabel("C (blue: input at its low value; red: at its high value)")
        ax.grid(alpha=0.3, axis="x")
        ax.legend(fontsize=7, loc="lower right")
    fig.suptitle(f"A5-CL tornado at the {PC['cap_duty'].value * 100:.0f} % duty cap, twelve largest of {len(swept_params())} swept inputs")
    fig.tight_layout()
    fig.savefig(out / "cl_tornado.png", dpi=105)
    plt.close(fig)


# ------------------------------------------------------------------------------------------ main
def write_csv(path, rows):
    rows = [{k: x for k, x in rr.items() if k != "trace"} for rr in rows]
    with open(path, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        w.writeheader()
        for rr in rows:
            w.writerow({k: (f"{x:.4f}" if isinstance(x, float) else x) for k, x in rr.items()})


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--run-id", default="2026-09-29-a5-closure-r1")
    ap.add_argument("--no-ltspice", action="store_true")
    ap.add_argument("--quick", action="store_true", help="tornado on 12 inputs only (development)")
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    t_start = time.time()
    out = HERE / "results" / a.run_id
    out.mkdir(parents=True, exist_ok=True)
    v0 = vals()

    with open(out / "inputs.csv", "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["name", "value", "low", "high", "unit", "class", "source", "in_tornado", "added_by_28a"])
        sw = set(swept_params())
        for k, p in PC.items():
            w.writerow([k, p.value, p.low, p.high, p.unit, p.cls, p.source,
                        "yes" if k in sw else ("closed-loop cases" if k in SENSOR_PARAMS else "no (fixed)"),
                        "yes" if k in P_ADD else "no"])

    params = swept_params()
    if a.quick:
        params = ["k_orient", "r_feed", "p_lm2940", "a5_idd", "g_cell_main", "h_out_c", "h_in_c", "a_mw",
                  "main_vent_area", "relay_hold", "k_cat", "eta_wall"]
    base, tor = {}, []
    for L in LAYOUTS:
        b, rows = tornado(L, params)
        base[L] = b
        tor += rows
        print(f"tornado {L} done at {time.time() - t_start:.0f} s", flush=True)
    bands = bands_from(tor)
    bands_ns = bands_from(tor, exclude=SINK_PATH)
    inh_rows, inh_tr, x_prop = inhibit_study("A5-CL", v0)
    print(f"inhibit done at {time.time() - t_start:.0f} s; proposed setpoint {x_prop:.1f} C", flush=True)
    bs = backstop_study("A5-CL", v0)
    cp = cap_pattern("A5-CL", v0, x_prop)
    S = duty_limit_S("A5-CL", v0)
    bench = bench_acceptance("A5-CL", bands_ns, v0)
    print(f"cases done at {time.time() - t_start:.0f} s", flush=True)
    sweep = {}
    for L in ("A5-DC/CAP", "A5-CL"):
        sweep[L] = []
        for d in np.round(np.arange(0.20, 0.7001, 0.05), 2):
            net = build(L, 45.0, v0)
            T = net.steady(float(d))
            sweep[L].append(dict(layout=L, duty=float(d), tj_pk=r.periodic_peak(net, float(d))[0], case_d=T["CASE"],
                                 petg_d=max(m.petg_hot_faces(net, T, v0).values()), bay_d=T["BAY"],
                                 cell_d=T["CELL"], main_d=T["MAIN"]))
    vs = verdict_set(base, bands, inh_rows, bs, v0)
    block = render_block(vs)
    values = render_values(base, inh_rows, x_prop, S, bench, v0, cp, vs)

    write_csv(out / "tornado.csv", tor)
    write_csv(out / "bands.csv", [dict(layout=b["layout"], metric=b["metric"], base=base[b["layout"]][b["metric"]],
                                       band_up=b["up"], band_dn=b["dn"], band_up_without_sink_path=bands_ns[k]["up"],
                                       largest_inputs=b["top"]) for k, b in bands.items()])
    write_csv(out / "verdict_set.csv", vs)
    write_csv(out / "inhibit.csv", inh_rows)
    write_csv(out / "backstop.csv", bs)
    write_csv(out / "duty_sweep.csv", [x for rows in sweep.values() for x in rows])
    write_csv(out / "bench_acceptance.csv", bench["rows"])
    write_csv(out / "summary.csv", [dict(layout=L, **{k: x for k, x in base[L].items()}) for L in LAYOUTS])
    write_csv(out / "cap_pattern.csv", [dict(node=n, last_hour_max=x) for n, x in cp["last_hour_max"].items()]
              + [dict(node="PETG hottest face", last_hour_max=cp["petg_last_hour_max"]),
                 dict(node="key-down fraction after 1 h", last_hour_max=cp["duty_actual"])])

    plot_vs_duty(out, sweep, base, bands, v0)
    plot_margins(out, vs)
    plot_inhibit(out, inh_tr, inh_rows, bs, v0, x_prop)
    plot_cap(out, cp, base, v0)
    plot_bench(out, bench, v0)
    plot_tornado(out, tor, bands)
    lt = ltspice_check(out) if not a.no_ltspice else dict(ok=False, msg="skipped")

    sd = out / "scripts"
    sd.mkdir(exist_ok=True)
    for fn in ("a5_closure.py", "thermal_model.py", "ts012_thermal.py"):
        shutil.copy2(HERE / fn, sd / fn)
    shas = {fn: hashlib.sha256((HERE / fn).read_bytes()).hexdigest() for fn in ("a5_closure.py", "thermal_model.py", "ts012_thermal.py")}

    lines = ["# WP-PDR-28a A5 thermal closure: results", "",
             f"Run id `{out.name}`; runner `hardware/sim/thermal/a5_closure.py` on the unchanged `thermal_model.py` and "
             "`ts012_thermal.py` of the TS-012 thermal note (copies and SHA-256 below). Every temperature is an **estimate**.", "",
             f"Tornado: {len(params)} swept inputs x {len(LAYOUTS)} layouts; duty of A5-DC/DL re-found for every input value.", "",
             "## Verdict set", "", block, "", "## Proposed values", "", values, "",
             "## Duty at which each layout is evaluated", ""]
    for L in LAYOUTS:
        lines.append(f"- {L}: {base[L]['duty'] * 100:.1f} % ({LAYOUTS[L]['duty']}); duty band "
                     f"+{bands[(L, 'duty')]['up'] * 100:.1f} / -{bands[(L, 'duty')]['dn'] * 100:.1f} points")
    lines += ["", "## REQ-SYS-118 inhibit on the flange NTC, closed loop, key held 60 min from a 45 C soak", "",
              "| Case | Own largest setpoint, C | Junction max at the proposed setpoint, C | Case max, C | Sink max, C | PA-bay air max, C | LM2940 junction max, C | RF-off events |",
              "|---|---|---|---|---|---|---|---|"]
    for x in inh_rows:
        lines.append(f"| {x['case']} | {x['setpoint_case']:.1f}{'' if x['setpoint_largest'] else ' (not confirmed largest)'} | {x['tj_max']:.2f} | "
                     f"{x['case_max']:.2f} | {x['sink_max']:.2f} | {x['bay_max']:.2f} | {x['lm_max']:.2f} | {x['n_offs']} |")
    lines += ["", "## REQ-SYS-181 backstop alone (sink NTC, 98 C edge), key held 3 h from a 45 C soak", "",
              "| Case | Channel max, C | Case max, C | Sink max, C | LM2940 junction max, C | RF-off events |", "|---|---|---|---|---|---|"]
    for x in bs:
        lines.append(f"| {x['case']} | {x['tj_max']:.2f} | {x['case_max']:.2f} | {x['sink_max']:.2f} | {x['lm_max']:.2f} | {x['n_offs']} |")
    lines += ["", "## Worst burst pattern under the duty cap (last hour of 4 h)", "",
              "| Node | Max, C |", "|---|---|"]
    for n, x in cp["last_hour_max"].items():
        lines.append(f"| {n} | {x:.2f} |")
    lines += [f"| hottest PETG face | {cp['petg_last_hour_max']:.2f} |",
              f"| key-down fraction after the first hour | {cp['duty_actual'] * 100:.2f} % |", "",
              "## Bench acceptance of the in-situ sink", "",
              f"- non-sink band of the junction peak at the cap: +{bench['band_tj']:.2f} K; of the case: +{bench['band_case']:.2f} K",
              f"- k_orient at the junction bound {bench['k_tj']:.3f}, at the case bound {bench['k_case']:.3f}; accepted up to {bench['k_acc']:.3f}",
              f"- bench resistance at 5.0 W: model nominal {bench['R5_nom']:.3f} K/W, acceptance at most {bench['R5_acc']:.2f} K/W",
              f"- bench resistance at 10.0 W: model nominal {bench['R10_nom']:.3f} K/W, acceptance at most {bench['R10_acc']:.2f} K/W",
              "", "## LTspice cross-check (A5-CL at the cap, electrical analogue)", ""]
    if lt.get("ok"):
        lines.append(f"LTspice 26.0.2 through tools/ltspice-batch.sh; deck SHA-256 `{lt['deck_sha256']}`; maximum difference after 30 s "
                     f"**{lt['maxdiff']:.3f} K** (criterion 0.5 K): **{'PASS' if lt['maxdiff'] <= 0.5 else 'FAIL'}**.")
        lines += ["", "| Node | LTspice at 14400 s | Python at 14400 s | Python steady | max diff, K |", "|---|---|---|---|---|"]
        for n, d in lt["nodes"].items():
            lines.append(f"| {n} | {d['lt_end']:.2f} | {d['py_end']:.2f} | {d['ss']:.2f} | {d['maxdiff']:.3f} |")
    else:
        lines.append(f"Not run or failed: {lt}")
    lines += ["", "## Uncertainty bands, three largest inputs", ""]
    for (L, k), b in bands.items():
        lines.append(f"- {L} {METRICS.get(k, k)}: +{b['up']:.2f} / -{b['dn']:.2f}; {b['top']}")
    lines += ["", "## Scripts", ""] + [f"- `{fn}` SHA-256 `{s}`" for fn, s in shas.items()]
    lines += ["", f"Run time {time.time() - t_start:.0f} s."]
    (out / "results.md").write_text("\n".join(lines) + "\n")
    print((out / "results.md").read_text())
    if a.check:
        sys.exit(check(block, values, lt))


def check(block, values, lt):
    errors = []
    text = NOTE.read_text() if NOTE.exists() else ""
    for beg, end, comp, what in ((VS_BEGIN, VS_END, block, "verdict set"), (PV_BEGIN, PV_END, values, "proposed values")):
        if beg not in text or end not in text:
            errors.append(f"{what} markers not found in {NOTE}")
            continue
        stated = text[text.index(beg): text.index(end) + len(end)].strip().splitlines()
        computed = comp.strip().splitlines()
        for i in range(max(len(stated), len(computed))):
            s = stated[i] if i < len(stated) else "<missing>"
            c = computed[i] if i < len(computed) else "<missing>"
            if s.strip() != c.strip():
                errors.append(f"{what} line {i + 1}:\n  note:     {s}\n  computed: {c}")
    if not lt.get("ok"):
        errors.append(f"LTspice cross-check not run or failed: {lt.get('msg', lt)}")
    elif lt["maxdiff"] > 0.5:
        errors.append(f"LTspice cross-check {lt['maxdiff']:.3f} K exceeds 0.5 K")
    if errors:
        print(f"CHECK FAIL: {len(errors)} difference(s)")
        for e in errors:
            print(e)
        return 1
    print("CHECK PASS: the record's verdict set and proposed values equal the computed ones; LTspice within 0.5 K")
    return 0


if __name__ == "__main__":
    main()
