// @design cwht-app/main
// @target-only
//! # `cwht-app`: composition root of the cwht firmware (RP2350, target only)
//!
//! Claims the board, constructs the drivers and runs the main loop; all decisions live in
//! `cwht-core` (07 section 1.2, CS-38). Build increment FW-B0 (07 section 3.2) composes the
//! heartbeat of `cwht_core::heartbeat` on the Pico 2 on-board LED (GPIO25), which is the
//! toolchain-proof image of TC-SW-TOOL-001.

#![no_std]
#![no_main]
#![forbid(unsafe_code)]

use core::hint::spin_loop;
use core::panic::PanicInfo;

use api::gpio::Gpio;
use cwht_core::heartbeat::{BLINK_HALF_PERIOD_SPINS, Heartbeat, spin_wait};
use pico2::common::board::Rp2350;
use pico2::gpio::gpio::Rp2350Gpio;

/// Entry shim generated by `pico2::entry!`. It sits in a private module because the macro
/// emits an undocumented `pub` function, which `missing_docs` (CS-25) would reject at the
/// crate root; the exported symbol `__rustos_main` is the same either way.
mod entry {
    pico2::entry!(super::main);
}

/// Application entry point, tail-called by the rustos reset handler.
fn main() -> ! {
    // CS-11: the board take is the single permitted Option check; None halts.
    let Some(board) = Rp2350::take() else {
        safe_state_halt()
    };
    let mut gpio = Rp2350Gpio::new(board.gpio);
    // Second decision in target-only code, outside CS-11 and CS-38 as written: the rustos
    // driver constructor returns Result<_, GpioError>, so its failure arm halts. Recorded as
    // deviation D8 of docs/vv/reports/TC-SW-TOOL-001-r1.md section 2 (INSP-016 finding-2);
    // docs/cm/cr/CR-001-cs11-cs38-driver-construction-arms.md amends CS-11 and CS-38 to admit
    // driver-construction failure arms that call safe_state_halt(); owner disposition before FW-B1.
    let Ok(mut led) = gpio.output_from_handle(board.pins.led) else {
        safe_state_halt()
    };
    let mut heartbeat = Heartbeat::new();
    loop {
        // The pico2 output pin's error type is Infallible, so this pattern is irrefutable.
        let Ok(_level) = heartbeat.step(&mut led);
        spin_wait(BLINK_HALF_PERIOD_SPINS, spin_loop);
    }
}

/// Halt with the outputs as the drivers left them (FW-B0 has no safe-state outputs yet;
/// the safe-state manager of 07 section 14 replaces this from FW-B1).
fn safe_state_halt() -> ! {
    loop {
        spin_loop();
    }
}

/// Panic handler: halts only. The CS-12 content (safe-state register writes, panic marker in
/// the event log, watchdog reset request) is deferred to build increment FW-B1 (07 section
/// 3.2), when the safe-state manager and its outputs exist; FW-B0 drives no safe-state
/// output. Deferral recorded in docs/vv/reports/TC-SW-TOOL-001-r1.md section 9, deferral
/// FD-1 (INSP-016 finding-3).
#[panic_handler]
fn panic(_info: &PanicInfo) -> ! {
    safe_state_halt()
}
