#!/usr/bin/env python3
"""Unsafe-code audit for the cwht firmware (07 CS-05, CS-06, CS-07; MSR-11; gate G5).

Scans Rust sources for the `unsafe` keyword outside comments and literals and
classifies every site (block, fn, impl, trait, extern block, unsafe attribute).

* Audited roots (default: rustos `api` and `firmware/pico2`, the only crates
  permitted to contain `unsafe`, CS-05): every site needs a `// SAFETY:`
  comment immediately above it (CS-06). The comment block is the run of
  comment lines directly above the line holding the site, attribute lines
  (`#[...]`) skipped; one of its lines must start with `SAFETY:` after the
  comment marker (`//` or `///`). The SAFETY text is that line and the
  comment lines after it in the block.
  An `unsafe fn(..)` or `unsafe extern "C" fn(..)` function-pointer type is
  not a site (it declares no unsafe code).
* Forbidden roots (default: `firmware/`, the cwht workspace, whose crates carry
  `#![forbid(unsafe_code)]`): any site is a failure (CS-05). `target/`
  directories are never scanned.
* The audit list `firmware/unsafe-audit.md` (CS-07; 05 Table 4-1 row 46) is
  generated by `--write` from the scan: one row per audited site with file,
  line, kind, enclosing item and SAFETY text, plus the two hand-filled
  signature cells Reviewer (`INSP-NNN`) and Date (`YYYY-MM-DD`). A rewrite
  keeps the signature of every site whose file, kind, item and SAFETY text
  are unchanged (the line may move); the signature of a changed or removed
  site is moved to the "Superseded signatures" section, which is only ever
  appended to (signatures are never removed, 05 Table 4-1 row 46).

`--check` (the gate G5 form) fails when a site lacks its SAFETY comment, when
a forbidden root holds a site, when the audit list is absent or differs from
the scan (file, line, kind, item or SAFETY text), or when a signature cell is
malformed. Unsigned entries are reported (MSR-11) and fail only with
`--gate CDR`, `TRR` or `SAR` (07 section 8.2 Security row: "any unsigned
unsafe entry at CDR or SAR"; CS-07 requires the signatures before CDR, so
every later gate holds them too).

Usage:
    .venv/bin/python tools/unsafe_audit.py --check [--gate REVIEW] [--json]
    .venv/bin/python tools/unsafe_audit.py --write
    options: --root PATH (repository root, default the parent of tools/)
             --audited DIR (repeatable; default ../rustos/api and ../rustos/firmware/pico2)
             --forbidden DIR (repeatable; default firmware)
             --audit-file PATH (default firmware/unsafe-audit.md)

Exit status: 0 no failure; 1 a failure (listed as FAIL lines); 2 usage error
(unknown option or gate, a root that is not a directory).

Known-answer test: tools/tests/test_unsafe_audit.py on tools/tests/fixtures/unsafe_audit/.
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_AUDITED = ("../rustos/api", "../rustos/firmware/pico2")
DEFAULT_FORBIDDEN = ("firmware",)
DEFAULT_AUDIT_FILE = "firmware/unsafe-audit.md"
SIGNED_GATES = ("CDR", "TRR", "SAR")
GATES = ("SRR", "PDR", "CDR", "TRR", "SAR")
KINDS = ("block", "fn", "impl", "trait", "extern", "attr", "other")
INSP = re.compile(r"^INSP-[0-9]{3}$")
ISO = re.compile(r"^[0-9]{4}-[0-9]{2}-[0-9]{2}$")
TABLE_HEADER = "| # | File | Line | Kind | Item | SAFETY text | Reviewer | Date |"
SUPERSEDED_HEADER = "| File | Kind | Item | SAFETY text | Reviewer | Date | Superseded on |"


# ----------------------------------------------------------------------------
# Lexing: mask comments and literals, keep the comment text per line
# ----------------------------------------------------------------------------


def mask_rust(text: str) -> tuple[str, dict[int, list[str]]]:
    """Return (code, comments): code has every comment and literal body replaced by spaces
    (newlines kept, so offsets and line numbers are those of text); comments maps a 0-based
    line number to the text of each // comment on that line, marker removed."""
    out = list(text)
    comments: dict[int, list[str]] = {}
    i, n, line = 0, len(text), 0

    def blank(a: int, b: int) -> None:
        for k in range(a, b):
            if out[k] != "\n":
                out[k] = " "

    while i < n:
        c = text[i]
        if c == "\n":
            line += 1
            i += 1
            continue
        if text.startswith("//", i):
            end = text.find("\n", i)
            end = n if end == -1 else end
            body = text[i + 2:end]
            if body.startswith(("/", "!")):
                body = body[1:]
            comments.setdefault(line, []).append(body.strip())
            blank(i, end)
            i = end
            continue
        if text.startswith("/*", i):
            depth, j = 1, i + 2
            while j < n and depth:
                if text.startswith("/*", j):
                    depth, j = depth + 1, j + 2
                elif text.startswith("*/", j):
                    depth, j = depth - 1, j + 2
                else:
                    j += 1
            line += text.count("\n", i, j)
            blank(i, j)
            i = j
            continue
        raw = re.match(r"(?:br|cr|r)(#*)\"", text[i:i + 260]) if c in "bcr" and (i == 0 or not (text[i - 1].isalnum() or text[i - 1] == "_")) else None
        if raw:
            hashes = raw.group(1)
            start = i + raw.end()
            close = text.find('"' + hashes, start)
            end = n if close == -1 else close + 1 + len(hashes)
            line += text.count("\n", i, end)
            blank(start, max(start, end - 1 - len(hashes)))
            i = end
            continue
        if c == '"':
            j = i + 1
            while j < n and text[j] != '"':
                j += 2 if text[j] == "\\" else 1
            end = min(n, j + 1)
            line += text.count("\n", i, end)
            blank(i + 1, end - 1)
            i = end
            continue
        if c == "'":
            if i + 1 < n and text[i + 1] == "\\":
                j = i + 3  # the escaped character itself may be a quote ('\'')
                while j < n and text[j] != "'":
                    j += 1
                blank(i + 1, j)
                i = j + 1
                continue
            if i + 2 < n and text[i + 2] == "'":
                blank(i + 1, i + 2)
                i += 3
                continue
        i += 1
    return "".join(out), comments


# ----------------------------------------------------------------------------
# Sites
# ----------------------------------------------------------------------------


@dataclass
class Site:
    file: str  # display path
    line: int  # 1-based
    kind: str
    item: str
    safety: str  # empty when missing
    forbidden: bool = False

    def key(self) -> tuple[str, str, str, str]:
        return (self.file, self.kind, self.item, self.safety)


UNSAFE = re.compile(r"\bunsafe\b")
FN_NAME = re.compile(r"\bfn\s+([A-Za-z_][A-Za-z0-9_]*)")
ITEM_NAME = re.compile(r"\b(?:fn|static|const|struct|enum|union|mod|trait|type)\s+(?:mut\s+)?([A-Za-z_][A-Za-z0-9_]*)")


def classify(code: str, after: int) -> str:
    rest = code[after:after + 200].lstrip()
    if rest.startswith("{"):
        return "block"
    if rest.startswith("("):
        return "attr"
    word = re.match(r"[A-Za-z_]+", rest)
    token = word.group(0) if word else ""
    if token == "fn":
        return "type" if re.match(r"fn\s*\(", rest) else "fn"
    if token in ("impl", "trait"):
        return token
    if token == "extern":
        tail = rest[len("extern"):].lstrip()
        tail = re.sub(r'^"[^"]*"', "", tail).lstrip()  # the ABI string (masked to spaces inside)
        if tail.startswith("fn"):
            return "type" if re.match(r"fn\s*\(", tail) else "fn"
        return "extern"
    return "other"


def fn_spans(code: str) -> list[tuple[int, int, str]]:
    """(body start, body end, name) of every fn with a body."""
    spans = []
    for m in FN_NAME.finditer(code):
        j = m.end()
        while j < len(code) and code[j] not in "{;":
            j += 1
        if j >= len(code) or code[j] == ";":
            continue
        depth, k = 0, j
        while k < len(code):
            if code[k] == "{":
                depth += 1
            elif code[k] == "}":
                depth -= 1
                if depth == 0:
                    break
            k += 1
        spans.append((j, k, m.group(1)))
    return spans


def item_name(code: str, offset: int, kind: str, spans: list[tuple[int, int, str]]) -> str:
    if kind == "fn":
        m = FN_NAME.search(code, offset, offset + 400)
        return m.group(1) if m else "?"
    if kind == "attr":
        m = ITEM_NAME.search(code, offset, offset + 400)
        return m.group(1) if m else "?"
    if kind == "extern":
        return "extern block"
    if kind in ("impl", "trait"):
        end = code.find("{", offset)
        head = code[offset:end if end != -1 else offset + 120]
        head = re.sub(r"\s+", " ", head).strip()
        return head[len("unsafe "):] if head.startswith("unsafe ") else head
    inner = [s for s in spans if s[0] < offset < s[1]]
    if inner:
        return min(inner, key=lambda s: s[1] - s[0])[2]
    return "(module level)"


def safety_text(lines: list[str], code_lines: list[str], comments: dict[int, list[str]], index: int) -> str:
    """SAFETY text of the comment block directly above 0-based line index, or ''."""
    block: list[str] = []
    k = index - 1
    while k >= 0:
        stripped = lines[k].strip()
        if code_lines[k].strip() == "" and k in comments:
            block.insert(0, " ".join(comments[k]))
        elif stripped.startswith(("#[", "#![")):
            pass
        else:
            break
        k -= 1
    for j, text in enumerate(block):
        if text.startswith("SAFETY:"):
            return " ".join(t for t in block[j:] if t).strip()
    return ""


def scan_file(path: Path, display: str, forbidden: bool) -> list[Site]:
    text = path.read_text(encoding="utf-8", errors="replace")
    code, comments = mask_rust(text)
    lines, code_lines = text.split("\n"), code.split("\n")
    spans = fn_spans(code)
    sites = []
    for m in UNSAFE.finditer(code):
        kind = classify(code, m.end())
        if kind == "type":
            continue  # an `unsafe fn(..)` pointer type declares no unsafe code
        index = code.count("\n", 0, m.start())
        sites.append(Site(display, index + 1, kind, item_name(code, m.start(), kind, spans), safety_text(lines, code_lines, comments, index), forbidden))
    return sites


def rust_files(directory: Path) -> list[Path]:
    return sorted(p for p in directory.rglob("*.rs") if "target" not in p.relative_to(directory).parts)


def display_path(path: Path, root: Path) -> str:
    base = root.parent.resolve()
    try:
        return str(path.resolve().relative_to(base))
    except ValueError:
        return str(path.resolve())


def scan(root: Path, audited: list[Path], forbidden: list[Path]) -> list[Site]:
    sites: list[Site] = []
    for group, is_forbidden in ((audited, False), (forbidden, True)):
        for directory in group:
            for path in rust_files(directory):
                sites.extend(scan_file(path, display_path(path, root), is_forbidden))
    return sites


# ----------------------------------------------------------------------------
# Audit list
# ----------------------------------------------------------------------------


@dataclass
class Entry:
    file: str
    line: int
    kind: str
    item: str
    safety: str
    reviewer: str = ""
    date: str = ""

    def key(self) -> tuple[str, str, str, str]:
        return (self.file, self.kind, self.item, self.safety)


@dataclass
class AuditList:
    entries: list[Entry] = field(default_factory=list)
    superseded: list[list[str]] = field(default_factory=list)


def cell(text: str) -> str:
    return text.replace("\\", "\\\\").replace("|", "\\|")


def split_row(line: str) -> list[str]:
    cells, current, i, body = [], [], 0, line.strip()[1:-1] if line.strip().endswith("|") else line.strip()[1:]
    while i < len(body):
        if body[i] == "\\" and i + 1 < len(body):
            current.append(body[i + 1])
            i += 2
            continue
        if body[i] == "|":
            cells.append("".join(current).strip())
            current = []
        else:
            current.append(body[i])
        i += 1
    cells.append("".join(current).strip())
    return cells


def parse_audit(text: str) -> AuditList:
    audit = AuditList()
    section = None
    for line in text.splitlines():
        if line.strip() == TABLE_HEADER:
            section = "entries"
            continue
        if line.strip() == SUPERSEDED_HEADER:
            section = "superseded"
            continue
        if not line.startswith("|") or re.match(r"^\|[-| :]+\|$", line.strip()):
            if not line.startswith("|"):
                section = None if line.startswith("#") else section
            continue
        cells = split_row(line)
        if section == "entries" and len(cells) == 8:
            try:
                audit.entries.append(Entry(cells[1], int(cells[2]), cells[3], cells[4], "" if cells[5] == "(none: CS-06 violation)" else cells[5], cells[6], cells[7]))
            except ValueError:
                continue
        elif section == "superseded" and len(cells) == 7:
            audit.superseded.append(cells)
    return audit


def render_audit(entries: list[Entry], superseded: list[list[str]]) -> str:
    out = [
        "# Unsafe-code audit list",
        "",
        "Generated by `tools/unsafe_audit.py --write` (07 CS-06 and CS-07; 05 Table 4-1 row 46). Do not edit any cell",
        "except Reviewer (`INSP-NNN` of the code review record that checked the SAFETY argument, 07 CS-07) and Date",
        "(`YYYY-MM-DD` of that signature). A rewrite keeps each signature while the site's file, kind, item and SAFETY",
        "text are unchanged, and moves the signature of a changed or removed site to the last section, which is only",
        "appended to. Every entry is signed before CDR and re-signed at SAR when it changed (CS-07; MSR-11).",
        "",
        "## Sites",
        "",
        TABLE_HEADER,
        "|---|---|---|---|---|---|---|---|",
    ]
    for n, e in enumerate(entries, 1):
        out.append(f"| {n} | {cell(e.file)} | {e.line} | {e.kind} | {cell(e.item)} | {cell(e.safety) or '(none: CS-06 violation)'} | {cell(e.reviewer)} | {cell(e.date)} |")
    out += ["", "## Superseded signatures", "", SUPERSEDED_HEADER, "|---|---|---|---|---|---|---|"]
    for row in superseded:
        out.append("| " + " | ".join(cell(c) for c in row) + " |")
    return "\n".join(out) + "\n"


def regenerate(sites: list[Site], old: AuditList, today: str) -> tuple[list[Entry], list[list[str]]]:
    audited = [s for s in sites if not s.forbidden]
    pool: dict[tuple[str, str, str, str], list[Entry]] = {}
    for e in old.entries:
        pool.setdefault(e.key(), []).append(e)
    entries = []
    for s in audited:
        signed = pool.get(s.key())
        prior = signed.pop(0) if signed else None
        entries.append(Entry(s.file, s.line, s.kind, s.item, s.safety, prior.reviewer if prior else "", prior.date if prior else ""))
    superseded = [list(r) for r in old.superseded]
    for left in pool.values():
        for e in left:
            if e.reviewer or e.date:
                superseded.append([e.file, e.kind, e.item, e.safety, e.reviewer, e.date, today])
    return entries, superseded


# ----------------------------------------------------------------------------
# Check
# ----------------------------------------------------------------------------


def counts(sites: list[Site], entries: list[Entry] | None) -> dict[str, int]:
    audited = [s for s in sites if not s.forbidden]
    result = {kind: sum(1 for s in audited if s.kind == kind) for kind in KINDS}
    result["total"] = len(audited)
    result["without_safety"] = sum(1 for s in audited if not s.safety)
    result["forbidden_sites"] = sum(1 for s in sites if s.forbidden)
    result["unsigned"] = sum(1 for e in entries if not (e.reviewer and e.date)) if entries is not None else len(audited)
    return result


def check(sites: list[Site], audit: AuditList | None, audit_name: str, gate: str | None) -> tuple[list[str], list[str]]:
    """Return (failures, notes)."""
    failures, notes = [], []
    for s in sites:
        if s.forbidden:
            failures.append(f"{s.file}:{s.line} unsafe {s.kind} in a crate that forbids unsafe code (CS-05)")
        elif not s.safety:
            failures.append(f"{s.file}:{s.line} unsafe {s.kind} ({s.item}) without a // SAFETY: comment immediately above (CS-06)")
    audited = [s for s in sites if not s.forbidden]
    if audit is None:
        failures.append(f"{audit_name} does not exist; generate it with tools/unsafe_audit.py --write (CS-07)")
        return failures, notes
    scanned = [(s.file, s.line, s.kind, s.item, s.safety) for s in audited]
    listed = [(e.file, e.line, e.kind, e.item, e.safety) for e in audit.entries]
    if scanned != listed:
        missing = [r for r in scanned if r not in listed]
        extra = [r for r in listed if r not in scanned]
        for r in missing:
            failures.append(f"{audit_name} lacks the site {r[0]}:{r[1]} {r[2]} ({r[3]}); re-run --write (CS-07)")
        for r in extra:
            failures.append(f"{audit_name} lists {r[0]}:{r[1]} {r[2]} ({r[3]}), which the scan does not find as written; re-run --write (CS-07)")
        if not missing and not extra:
            failures.append(f"{audit_name} lists the sites in another order than the scan; re-run --write (CS-07)")
    for n, e in enumerate(audit.entries, 1):
        if e.reviewer and not INSP.match(e.reviewer):
            failures.append(f"{audit_name} row {n}: Reviewer '{e.reviewer}' is not INSP-NNN (CS-07)")
        if e.date and not ISO.match(e.date):
            failures.append(f"{audit_name} row {n}: Date '{e.date}' is not YYYY-MM-DD")
        if bool(e.reviewer) != bool(e.date):
            failures.append(f"{audit_name} row {n}: a signature needs both Reviewer and Date")
    unsigned = [n for n, e in enumerate(audit.entries, 1) if not (e.reviewer and e.date)]
    if unsigned:
        text = f"{len(unsigned)} unsigned entr{'y' if len(unsigned) == 1 else 'ies'} in {audit_name} (rows {', '.join(map(str, unsigned[:20]))}{', ...' if len(unsigned) > 20 else ''})"
        if gate in SIGNED_GATES:
            failures.append(text + f"; every entry is signed at {gate} (07 section 8.2; CS-07)")
        else:
            notes.append(text + "; signatures are required from CDR (07 section 8.2; CS-07)")
    return failures, notes


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0], formatter_class=argparse.RawDescriptionHelpFormatter)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true", help="check the sources and the audit list (gate G5)")
    mode.add_argument("--write", action="store_true", help="regenerate the audit list, keeping signatures")
    parser.add_argument("--root", type=Path, default=REPO_ROOT)
    parser.add_argument("--audited", type=Path, action="append", help="root that may hold unsafe with SAFETY comments (repeatable)")
    parser.add_argument("--forbidden", type=Path, action="append", help="root that may hold no unsafe (repeatable)")
    parser.add_argument("--audit-file", type=Path, default=None)
    parser.add_argument("--gate", choices=GATES, default=None, help="unsigned entries fail at CDR, TRR and SAR")
    parser.add_argument("--json", action="store_true", help="print the MSR-11 counts and the failures as JSON")
    parser.add_argument("--date", default=None, help="date written into superseded signatures (default today)")
    args = parser.parse_args(argv)
    root = args.root.resolve()
    if not root.is_dir():
        parser.error(f"root is not a directory: {root}")
    audited = [(root / p).resolve() for p in (args.audited or [Path(p) for p in DEFAULT_AUDITED])]
    forbidden = [(root / p).resolve() for p in (args.forbidden or [Path(p) for p in DEFAULT_FORBIDDEN])]
    for directory in audited + forbidden:
        if not directory.is_dir():
            parser.error(f"scan root is not a directory: {directory}")
    audit_path = (root / (args.audit_file or Path(DEFAULT_AUDIT_FILE))).resolve()
    audit_name = display_path(audit_path, root)
    sites = scan(root, audited, forbidden)
    old = parse_audit(audit_path.read_text(encoding="utf-8")) if audit_path.is_file() else None
    if args.write:
        entries, superseded = regenerate(sites, old or AuditList(), args.date or dt.date.today().isoformat())
        audit_path.write_text(render_audit(entries, superseded), encoding="utf-8")
        print(f"unsafe_audit: wrote {audit_name} ({len(entries)} sites, {len(superseded)} superseded signatures)")
        old = AuditList(entries, superseded)
    failures, notes = check(sites, old, audit_name, args.gate)
    measured = counts(sites, old.entries if old else None)
    if args.json:
        print(json.dumps({"msr_11": measured, "failures": failures, "notes": notes}, indent=2))
    else:
        for f in failures:
            print(f"FAIL {f}")
        for note in notes:
            print(f"NOTE {note}")
        print("MSR-11 unsafe sites: " + ", ".join(f"{k} {measured[k]}" for k in KINDS if measured[k]) + f"; total {measured['total']}; without SAFETY {measured['without_safety']}; unsigned {measured['unsigned']}; in forbidden crates {measured['forbidden_sites']}")
        print(f"unsafe_audit: {'FAIL' if failures else 'PASS'} ({len(failures)} failure(s))")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
